### ISSUE TITLE
July 8th changes to tournaments

### ISSUE THREAD

**Issue by Mu0n** [Killerardvark/Cryodex#3]
According to FFG's newest version of the tournament rules, pairings after round 1 are to be randomized between players with the same score (as much as possible), while still maintaining the restriction that players don't play each other more than once during the swiss rounds. Do you plan to add this to cryodex soon?

**Comment by Killerardvark** [comment]
The only remaining official FFG tournament this year is Worlds which will not be running Cryodex. My current plan is to let FFG figure their stuff out because obviously their tournament rules are in flux while they try to align their software and their rules. The plan is to have it fully updated and ready in January for the beginning of the new tournament season. If any of these assumptions are incorrect or their is a significant need for it to be updated before then we can discuss that. Thanks
